-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1zQyXa0PjHCMyoFf
a8IbSxyBdlXi2fVm7too27txOo2gCgYIKoZIzj0DAQehRANCAAQlVv2qU8np2gke
8NMpc8lZclbNKSpbwVJRFPbTh7IJ3JL+RlhVXNrydg9nlesAH8QFemBqauNlJs1k
y6U8B+Ap
-----END PRIVATE KEY-----