name: authenticator
description: "A secure SecureAuth Vault app for credentials, documents & sensitive data."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management & routing
  get: ^4.6.6

  # Authentication
  local_auth: ^2.3.0

  # Secure key storage (Keychain / Keystore backed)
  flutter_secure_storage: ^9.2.2

  # Local database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Encryption (AES-256)
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # File system
  path_provider: ^2.1.4

  # File picking / camera
  file_picker: ^8.1.2
  image_picker: ^1.1.2

  # Google Drive backup
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  http: ^1.2.2

  # Permissions
  permission_handler: ^11.3.1

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.2
  shared_preferences: ^2.3.2
  firebase_core: ^4.9.0
  otp: ^3.2.0
  mobile_scanner: ^7.2.0
  flutter_svg: ^2.3.0
  firebase_remote_config: ^6.5.1

  stac: ^1.5.0
  cloud_firestore: ^6.4.1
  carousel_slider: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
