// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGCa1M_atLFNzWWyprcBtjICxoD77IPA',
    appId: '1:868246110787:web:67a580d664d023eff80af6',
    messagingSenderId: '868246110787',
    projectId: 'fir-demo-1e8b7',
    authDomain: 'fir-demo-1e8b7.firebaseapp.com',
    storageBucket: 'fir-demo-1e8b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaU3tZxK0kQEjss4XD7Vj0Wa-VWCgaJM',
    appId: '1:868246110787:ios:1e811e569f954e30f80af6',
    messagingSenderId: '868246110787',
    projectId: 'fir-demo-1e8b7',
    storageBucket: 'fir-demo-1e8b7.firebasestorage.app',
    androidClientId: '868246110787-3mekj45r4nigcms1ebp2eo6oibumf16j.apps.googleusercontent.com',
    iosClientId: '868246110787-js1ejd8kncui6kkialo678ceunv3v1jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantOrder',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXoNgrlWWIQRefZUt6FAufc9ZpurH9bY',
    appId: '1:868246110787:android:f10ff84f96cc8d8ff80af6',
    messagingSenderId: '868246110787',
    projectId: 'fir-demo-1e8b7',
    storageBucket: 'fir-demo-1e8b7.firebasestorage.app',
  );
}
