// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBim_B2FTZdZtjrnSlwuf2KmipUvElOLzM',
    appId: '1:448917328599:android:fd561d16e278c26101d692',
    messagingSenderId: '448917328599',
    projectId: 'test-dynamic-icon-codex',
    storageBucket: 'test-dynamic-icon-codex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaU3tZxK0kQEjss4XD7Vj0Wa-VWCgaJM',
    appId: '1:868246110787:ios:134917b81c8c4c77f80af6',
    messagingSenderId: '868246110787',
    projectId: 'fir-demo-1e8b7',
    storageBucket: 'fir-demo-1e8b7.firebasestorage.app',
    androidClientId: '868246110787-3mekj45r4nigcms1ebp2eo6oibumf16j.apps.googleusercontent.com',
    iosClientId: '868246110787-toc4e5fr6lbp8qgj5hnucteqks1q0jh9.apps.googleusercontent.com',
    iosBundleId: 'com.secureAuthVault',
  );
}