// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rsZzG2cfMNRcSeUyhigx2745j4Fru6Q',
    appId: '1:679923746617:web:0615b6fbed1cfc89e54ae8',
    messagingSenderId: '679923746617',
    projectId: 'webrtc-demo-e307f',
    authDomain: 'webrtc-demo-e307f.firebaseapp.com',
    storageBucket: 'webrtc-demo-e307f.firebasestorage.app',
    measurementId: 'G-GEGNVT41HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcCOEn_J6QIESQEZpU3yo6K0ke2W4F2g',
    appId: '1:679923746617:android:e3fb1d043d3c867ce54ae8',
    messagingSenderId: '679923746617',
    projectId: 'webrtc-demo-e307f',
    storageBucket: 'webrtc-demo-e307f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKLz8ExO_eznP734LT_2ycCuodDr0Fw_I',
    appId: '1:679923746617:ios:2e9c0236d9463bbae54ae8',
    messagingSenderId: '679923746617',
    projectId: 'webrtc-demo-e307f',
    storageBucket: 'webrtc-demo-e307f.firebasestorage.app',
    androidClientId: '679923746617-o7365srhnbeuuuutvrbs9p0p9gu025na.apps.googleusercontent.com',
    iosClientId: '679923746617-3tksfs9kf3bif2sdcsfbr0743ccd6k2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.webRtc',
  );
}
